name: Refresh API Specs

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: 0 0 * * *

jobs: 
  update_specs:
    runs-on: ubuntu-latest
    strategy: 
      max-parallel: 1
      fail-fast: false
      matrix: 
        spec: 
          - v2-pcv2
          - v2-pcv1
          - v1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install yq
        uses: mikefarah/yq@master
      - name: Refresh API Specs
        run: |
          curl https://openapi.chargebee.com/${{ matrix.spec }}/index.json | yq -P -p=json -o=json 'del(.info.x-generated-on)' >| specs/${{matrix.spec}}/index.json
          curl https://openapi.chargebee.com/${{ matrix.spec }}/index.yaml | yq -P 'del(.info.x-generated-on)' >| specs/${{matrix.spec}}/index.yaml
      - name: check for changes
        uses: tj-actions/verify-changed-files@v16
        id: changed
        with: 
          files: |
            specs/${{ matrix.spec }}
      - name: Commit and push changes
        if: steps.changed.outputs.files_changed == 'true'
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          git pull
          git add .
          git commit -m "Refreshed API Spec ${{matrix.spec}} ${date}"
          git push